### ISSUE TITLE
Failed to install using pip3.4 - ImportError: No module named 'cPickle'

### ISSUE THREAD

**Issue by johnathanz** [python-rope/rope#124]
Hi there

I'm trying to install rope using pip3.4.

This is the error I'm getting:

---
▶ pip3.4 install rope
Collecting rope
  Downloading rope-0.10.2.tar.gz (221kB)
    100% |████████████████████████████████| 225kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/31/cx7rrjv50zgg_hw2tmd631000000gn/T/pip-build-x3qvzk0v/rope/setup.py", line 5, in <module>
        import ropetest
      File "/private/var/folders/31/cx7rrjv50zgg_hw2tmd631000000gn/T/pip-build-x3qvzk0v/rope/ropetest/__init__.py", line 4, in <module>
        import ropetest.projecttest
      File "/private/var/folders/31/cx7rrjv50zgg_hw2tmd631000000gn/T/pip-build-x3qvzk0v/rope/ropetest/projecttest.py", line 9, in <module>
        from rope.base.libutils import path_to_resource
      File "/private/var/folders/31/cx7rrjv50zgg_hw2tmd631000000gn/T/pip-build-x3qvzk0v/rope/rope/base/libutils.py", line 4, in <module>
        import rope.base.project
      File "/private/var/folders/31/cx7rrjv50zgg_hw2tmd631000000gn/T/pip-build-x3qvzk0v/rope/rope/base/project.py", line 1, in <module>
        import cPickle as pickle
    ImportError: No module named 'cPickle'

----

**Comment by mcepl** [comment]
Python 3 is still not supported. There are some rumours about the progress in #57 but nothing has got really done yet.
