### ISSUE TITLE
Failing tests, python2.7/RHEL-7

### ISSUE THREAD

**Issue by soupytwist** [python-rope/rope#183]
```
======================================================================
FAIL: test_time_in_std_mods (ropetest.builtinstest.BuiltinModulesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/builtinstest.py", line 503, in test_time_in_std_mods
    self.assertTrue('time' in rope.base.stdmods.standard_modules())
AssertionError: False is not true

======================================================================
FAIL: test_sorting_imports_and_standard_modules2 (ropetest.refactor.importutilstest.ImportUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/refactor/importutilstest.py", line 775, in test_sorting_imports_and_standard_modules2
    self.import_tools.sort_imports(pymod))
AssertionError: 'import sys\nimport time\n' != u'import sys\n\nimport time\n'

----------------------------------------------------------------------
Ran 1606 tests in 17.293s

FAILED (failures=2, skipped=4)
```

The above output from @mcepl on python2.7/RHEL-7, though these tests pass on Travis.

**Comment by mcepl** [comment]
There must be something strange my system, indeed. I cannot now pass even with commits I know for sure I have tested before. Keep this issue open please, but it is not blocking #182 .

**Comment by sergeyglazyrindev** [comment]
Hey Matej
Could you please let me know implementation of python ? Is there any specific stuff do you use or installed on your redhat  ? It works on my pc (CPython).

**Comment by mcepl** [comment]
system python of RHEL-7 (``python-2.7.5-58.el7.x86_64``). I don't think about anything special. Weird. Still failing with beb3ef9

**Comment by mcepl** [comment]
Not failing with python-2.7.5-68.el7.x86_64 and 0d79dddb. Thank you.
