### ISSUE TITLE
importerrors on master

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-rope/rope#199]
i installed master to rerun my scripts, and i got 

```
$ python ../fixup.py 
Traceback (most recent call last):
  File "../fixup.py", line 1, in <module>
    from rope.base.project import Project
  File "/home/ronny/Projects/RedHatQE/cfme_venv/lib/python2.7/site-packages/rope/base/project.py", line 6, in <module>
    import rope.base.fscommands
  File "/home/ronny/Projects/RedHatQE/cfme_venv/lib/python2.7/site-packages/rope/base/fscommands.py", line 13, in <module>
    import rope.base.utils.pycompat as pycompat
ImportError: No module named utils.pycompat
```

it seems a mistake in using relative vs absolute imports

**Comment by soupytwist** [comment]
Something's fishy. Can you check the code that you cloned look correct? All directories have `__init__.py`? How did you fetch the latest version of rope?

```
$ find rope -name __init__.py
rope/base/__init__.py
rope/base/oi/type_hinting/providers/__init__.py
rope/base/oi/type_hinting/__init__.py
rope/base/oi/type_hinting/resolvers/__init__.py
rope/base/oi/__init__.py
rope/base/utils/__init__.py
rope/contrib/__init__.py
rope/__init__.py
rope/refactor/__init__.py
rope/refactor/importutils/__init__.py
```

**Comment by RonnyPfannschmidt** [comment]
pip install from master, then editable pip install from my fork, i do have a local fix, will do a pr in a few seconds

**Comment by bmihelac** [comment]
I have similar issue. Installed in fresh virtualenv and `rope.base.utils` is missing. 

```
(testrope)➜  testrope pip install rope
Downloading/unpacking rope
  Downloading rope-0.10.4.tar.gz (243kB): 243kB downloaded
  Running setup.py egg_info for package rope
    
Installing collected packages: rope
  Running setup.py install for rope
    
Successfully installed rope
Cleaning up...
(testrope)➜  rope python
Python 2.7.3 (default, Oct 15 2013, 11:34:37) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.78)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rope.base.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named utils
>>> import rope.base
>>> 
```

**Comment by soupytwist** [comment]
Thank you all. I'll make sure to verify this in the future so this doesn't happen again.

New package (0.10.5) is available in pypi now.

Sorry for the trouble!

**Comment by RonnyPfannschmidt** [comment]
@soupytwist how about using setuptools and find_pacakges?

**Comment by soupytwist** [comment]
That's a good suggestion to revisit this.

**Comment by RonnyPfannschmidt** [comment]
@soupytwist btw, that brings #201 to mind
