### ISSUE TITLE
move/rename refactoring failures in combination with relative imports

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-rope/rope#202]
on a project i'm working on  i prepared a script for a larger code move
while testing it i noticed that it would fail on relative import

the related code changes for the script and ensuring it runs where made in manageiq/integration_tests#4067

the move script is https://github.com/RonnyPfannschmidt/manageiq_integration_tests/blob/3cf58675ecdfe7422d97c97127f62095c742903c/scripts/refactoring/provider_move.py

the needed changes to make it run to completion are https://github.com/ManageIQ/integration_tests/pull/4067/commits/a02b05f33405f2ec9461b39bf01b03dc8b9e0a35

the triggered output on error is
```
$ python scripts/refactoring/provider_move.py 
infrastructure
 append name
 move
 fix_name
 push up elements
  push up openstack_infra.py
  push up scvmm.py
  push up virtualcenter.py
  push up rhevm.py
 meshing up __init__.py
cloud
 append name
 move
 fix_name
 push up elements
  push up azure.py
  push up ec2.py
  push up gce.py
  push up openstack.py
 meshing up __init__.py
middleware
 append name
 move
Traceback (most recent call last):
  File "scripts/refactoring/provider_move.py", line 27, in <module>
    MoveModule(my_project, res).get_changes(providers_dest).do()
  File "/home/ronny/Projects/python-rope/rope/rope/refactor/move.py", line 454, in get_changes
    return self._calculate_changes(dest, resources, task_handle)
  File "/home/ronny/Projects/python-rope/rope/rope/refactor/move.py", line 466, in _calculate_changes
    resource=module)
  File "/home/ronny/Projects/python-rope/rope/rope/refactor/move.py", line 518, in _change_occurrences_in_module
    pymodule = self.tools.new_pymodule(pymodule, source)
  File "/home/ronny/Projects/python-rope/rope/rope/refactor/move.py", line 666, in new_pymodule
    self.project, source, pymodule.get_resource())
  File "/home/ronny/Projects/python-rope/rope/rope/base/libutils.py", line 94, in get_string_module
    force_errors=force_errors)
  File "/home/ronny/Projects/python-rope/rope/rope/base/pyobjectsdef.py", line 162, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/home/ronny/Projects/python-rope/rope/rope/base/pyobjectsdef.py", line 191, in _init_source
    raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)
rope.base.exceptions.ModuleSyntaxError: Syntax error in file <cfme/middleware/domain.py> line <15>: invalid syntax
´´´

the rope version is master as of yesterday

**Comment by soupytwist** [comment]
Thanks for the detailed report! Let me take a look. This may be related to `pull_imports_to_top=False`.

**Comment by RonnyPfannschmidt** [comment]
i did not use that setting in that getup

**Comment by soupytwist** [comment]
Ah, okay. I didn't look closely yet. Then I'm not sure what's the regression, will need to do some digging.

**Comment by RonnyPfannschmidt** [comment]
please do it as you find time and motivation, we fixed the problem locally by changing our own code and wont face a similar one soon

**Comment by abingham** [comment]
I'm seeing the same error when I run `MoveModule`. The refactoring takes relative imports like this:
```
from .submodule import name 
```
to:
```
frompackage.submodule import name
```

i.e. it seems to neglect to put a space between `from` and `package`. I see this in the exception produced when I try to perform the operation:
```
Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/traad/lib/python3.6/site-packages/rope/base/pyobjectsdef.py", line 189, in _init_source
    ast_node = ast.parse(source_bytes, filename=filename)
  File "/Users/abingham/.virtualenvs/traad/lib/python3.6/site-packages/rope/base/ast.py", line 21, in parse
    return compile(source, filename, 'exec', _ast.PyCF_ONLY_AST)
  File "src/euler/util.py", line 9
    fromeuler.lib.primes import Primes
                              ^
SyntaxError: invalid syntax
```

**Comment by rubendibattista** [comment]
Same here, I'm also getting a Syntax error with `ropevim` for a line of the type:

`from .state import State`

```
Calculating move_current_module changes ... 6%%
ModuleSyntaxError: Syntax error in file <josie/solver/problem.py> line <36>: invalid syntax
```

In order to help, where should I look?
