### ISSUE TITLE
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: [] (type_hinting_test:34)

### ISSUE THREAD

**Issue by nonamedotc** [python-rope/rope#247]
Some of the tests fail when built with python 3.7 on Fedora.

```
======================================================================
FAIL: test_hint_parametrized_iterable (ropetest.type_hinting_test.DocstringNoneAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 203, in test_hint_parametrized_iterable
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterator (ropetest.type_hinting_test.DocstringNoneAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 212, in test_hint_parametrized_iterator
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterable (ropetest.type_hinting_test.DocstringNotImplementedAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 203, in test_hint_parametrized_iterable
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterator (ropetest.type_hinting_test.DocstringNotImplementedAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 212, in test_hint_parametrized_iterator
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterable (ropetest.type_hinting_test.PEP0484CommentNoneAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 203, in test_hint_parametrized_iterable
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterator (ropetest.type_hinting_test.PEP0484CommentNoneAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 212, in test_hint_parametrized_iterator
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterable (ropetest.type_hinting_test.PEP0484CommentNotImplementedAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 203, in test_hint_parametrized_iterable
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
======================================================================
FAIL: test_hint_parametrized_iterator (ropetest.type_hinting_test.PEP0484CommentNotImplementedAssignmentHintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 212, in test_hint_parametrized_iterator
    self.assert_completion_in_result('isAlive', 'attribute', result)
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/type_hinting_test.py", line 34, in assert_completion_in_result
    [(i.name, i.scope) for i in result]
AssertionError: completion <isAlive> in scope 'attribute' not proposed, available names: []
----------------------------------------------------------------------
```

Here is the complete build.log - https://kojipkgs.fedoraproject.org//work/tasks/3559/27753559/build.log

Pointers to fix these would be greatly appreciated. Thanks!

**Comment by mcepl** [comment]
Of course, the same here on openSUSE.

**Comment by mcepl** [comment]
To my shame, still alive in 0.12.0.

**Comment by marv** [comment]
Any update on this? I'm still seeing the same test failures on Exherbo with rope 0.14.0

**Comment by mcepl** [comment]
See #283 for WIP on fixing this. @soupytwist , any ideas?
