### ISSUE TITLE
Rope fails to run `analyze_modules` on some projects

### ISSUE THREAD

**Issue by rbclark** [python-rope/rope#260]
I am having trouble running `analyze_modules` on my project. For some reason I am having a lot of trouble reproducing the error in an environment outside of my whole project. Basically what is happening is the following:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/libutils.py", line 81, in analyze_modules
    analyze_module(project, resource)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/libutils.py", line 69, in analyze_module
    project.pycore.analyze_module(resource)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/pycore.py", line 210, in analyze_module
    self, pymodule, should_analyze, search_subscopes, followed_calls)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 16, in analyze_module
    search_subscopes, followed_calls)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 24, in _analyze_node
    search_subscopes, followed_calls)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 24, in _analyze_node
    search_subscopes, followed_calls)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 76, in _Call
    self._call(pyfunction, args)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soa.py", line 88, in _call
    pyfunction, args.get_arguments(pyfunction.get_param_names()))
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/arguments.py", line 24, in get_arguments
    result.append(pyname.get_object())
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/soi.py", line 80, in infer_assigned_object
    hinting_result = hint_assignment(pyname)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/type_hinting/providers/inheritance.py", line 63, in __call__
    result = self._delegate(super_pyname)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/type_hinting/providers/composite.py", line 57, in __call__
    result = delegate(pyname)
  File "/Users/rbclark/.pyenv/versions/2.7.15/lib/python2.7/site-packages/rope/base/oi/type_hinting/providers/pep0484_type_comments.py", line 24, in __call__
    lineno = _get_lineno_for_node(pyname.assignments[0].ast_node)
AttributeError: 'EvaluatedName' object has no attribute 'assignments'
```

It seems that sometimes `pyname` in `pep0484_type_comments.py` is of a type that doesn't have an attributes object on it. I tried wrapping it in

```
try:
    lineno = _get_lineno_for_node(pyname.assignments[0].ast_node)
except AttributeError:
    return None
```

And it seemed to resolve the issue at least in that location. The error then started popping up in `base/oi/type_hinting/utils.py:45` for a similar reason.

**Comment by soupytwist** [comment]
Thanks for the detailed report and workaround!
