### ISSUE TITLE
Rename a python class name with a script

### ISSUE THREAD

**Issue by MichaelSchneeberger** [python-rope/rope#462]
**Describe the bug**
Renaming a python class with `rope.refactor.rename` does not update the import statement in other files of the project.

**To Reproduce**
1. Code before refactoring:

Given the following the project structure
```
proja
-- __init__.py
-- city.py
-- citycapitol.py
```

`city.py`
```
class City:
    pass
```

`citycapitol.py`
```
from pcka.city import City

class CityCapitol(City):
    pass
```

2. Describe the refactoring you want to do

```
import rope.refactor.rename
import rope.refactor.restructure

proj = rope.base.project.Project('pcka')
res = proj.get_module('city').get_resource()
offset = res.read().index(f'class City') + 6

change = rope.refactor.rename.Rename(
    proj, 
    res, 
    offset,
).get_changes('City2')
print(change.get_description())
```

3. Expected code after refactoring:

`city.py`
```
class City2:
    pass
```

`citycapitol.py`
```
from pcka.city import City2

class CityCapitol(City2):
    pass
```

4. Describe the error or unexpected result that you are getting

The import statement in `citycapitol.py` does not get adapted.

`citycapitol.py`
```
from pcka.city import City

class CityCapitol(City):
    pass
```

**Screenshots**

The `change.get_description()` returns the following

```
Renaming <City> to <City2>:

--- a/city.py
+++ b/city.py
@@ -1,2 +1,2 @@
-class City:
+class City2:
     pass
```

**Editor information (please complete the following information):**
 - Project Python version: 3.10.0
 - Rope Python version: 0.23.0

**Comment by lieryan** [comment]
Hi, sorry for the long reply. 

This is not a bug, but rather a configuration error. Because you're using `rope.base.project.Project('pcka')` as your project root, the two files `city.py` and `citycapitol.py` doesn't belong to the package.

Python behaved the same:

```

~/tmp$ ls -lahR *
-rw-rw-r-- 1 lieryan lieryan 342 Nov 29 01:51 renameref.py

pcka:
total 8.0K
drwxrwxr-x 1 lieryan lieryan  86 Nov 29 01:54 .
drwxrwxr-x 1 lieryan lieryan  78 Nov 29 01:51 ..
-rw-rw-r-- 1 lieryan lieryan  21 Nov 29 01:46 city.py
-rw-rw-r-- 1 lieryan lieryan  62 Nov 29 01:46 citycapitol.py
-rw-rw-r-- 1 lieryan lieryan   0 Nov 29 01:54 __init__.py
drwxrwxr-x 1 lieryan lieryan 142 Nov 29 01:54 __pycache__

~/tmp$ cd pcka

~/tmp/pcka$ python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import citycapitol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lieryan/tmp/462/pcka/citycapitol.py", line 1, in <module>
    from pcka.city import City
ModuleNotFoundError: No module named 'pcka'
$
```

To use rope properly in this setup, you would need to use the parent directory as the root directory, so that rope can see the package folder, so changing the code into this should make this work:

```
#!/usr/bin/env python
import rope.refactor.rename
import rope.refactor.restructure

proj = rope.base.project.Project('~/tmp')
res = proj.get_module('pcka.city').get_resource()
offset = res.read().index(f'class City') + 6

change = rope.refactor.rename.Rename(
    proj,
    res,
    offset,
).get_changes('City2')
print(change.get_description())
```

```
~/tmp/pcka$ cd ~/tmp

~/tmp$ python renameref.py
Renaming <City> to <City2>:


--- a/pcka/city.py
+++ b/pcka/city.py
@@ -1,2 +1,2 @@
-class City:
+class City2:
     pass

--- a/pcka/citycapitol.py
+++ b/pcka/citycapitol.py
@@ -1,4 +1,4 @@
-from pcka.city import City
+from pcka.city import City2
 
-class CityCapitol(City):
+class CityCapitol(City2):
     pass
```
