### ISSUE TITLE
[bug report] importError on python 3.4.4(win-x86), rope==0.22.0

### ISSUE THREAD

**Issue by RidiculousDoge** [python-rope/rope#521]
**Describe the bug**
ImportError occurrs when import rope on windows.

My version:
```
python==3.4.4 for x86
os == windows10
rope ==0.22.0
```
when I use `from rope.contrib.codeassist import code_assist`, I got ImportError:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\Python34x86\lib\site-packages\rope\contrib\codeassist.py", line 9, in <module>
    from rope.base import libutils
  File "C:\Python34\Python34x86\lib\site-packages\rope\base\libutils.py", line 4, in <module>
    import rope.base.project
  File "C:\Python34\Python34x86\lib\site-packages\rope\base\project.py", line 9, in <module>
    from rope.base import exceptions, taskhandle, prefs, history, pycore, utils
  File "C:\Python34\Python34x86\lib\site-packages\rope\base\pycore.py", line 18, in <module>
    from rope.base.pyobjectsdef import PyModule, PyPackage
  File "C:\Python34\Python34x86\lib\site-packages\rope\base\pyobjectsdef.py", line 7, in <module>
    import rope.base.pyscopes
  File "C:\Python34\Python34x86\lib\site-packages\rope\base\pyscopes.py", line 5, in <module>
    from rope.refactor import patchedast
  File "C:\Python34\Python34x86\lib\site-packages\rope\refactor\__init__.py", line 48, in <module>
    from rope.refactor.importutils import ImportOrganizer  # noqa
  File "C:\Python34\Python34x86\lib\site-packages\rope\refactor\importutils\__init__.py", line 8, in <module>
    from rope.base import libutils
ImportError: cannot import name 'libutils'
```

Sadly I have to use python3.4 to support windows xp. However, it raises error even on win10.

And I notice the highest version for `python3.4` is `rope==0.22.0`. I also tried downgrade the version, however it does not work on the first stage of `pip install`.

**To Reproduce**
1. Code before refactoring:

install python 3.4-32, and rope==0.22.0
```bash
py -3.4-32 -m pip install rope==0.22.0
```

run from bash:
```bash
py -3.4-32 -c "from rope.contrib.codeassist import code_assist"
```

**Comment by lieryan** [comment]
Can you reproduce this using a more recent version of rope and Python on Windows? 

If you want to research and write a PR to fix this and backport, I can help with merging it, but if this issue only ever happens on legacy/unsupported systems, this is unlikely to be fixed.

This is likely something to do with circular import order, if you do your imports in a different order, then this might not be an issue. Try importing `rope.base.project` before you import `rope.contrib.codeassist.code_assist` and see if it fixes the issue.

**Comment by lieryan** [comment]
Also, another workaround you might be able to do is to do your editing/refactoring using a more recent Python on a different machine. Python 3.4 are generally still close enough to Python 3.10, so that Python 3.10 parser likely still can parse code written for 3.4 and the code that the latest Rope that is running on Python 3.10 produce likely will still run just fine on Python 3.4.

**Comment by RidiculousDoge** [comment]
OK I now understand the reason. Seems like python 3.5 and higher support Circular imports.
