### ISSUE TITLE
Uncaught IndentationError in get_calltip

### ISSUE THREAD

**Issue by jorgenschaefer** [python-rope/rope#80]
This file generates an IndentationError. I would expect Rope to catch this error and either try to fix it using the usual maxfixes semantics, or throw a `ModuleSyntaxError` like for other such errors.

```Python
import shutil
import tempfile

import rope.base.project
import rope.contrib.codeassist


project_root = tempfile.mkdtemp()
try:

    project = rope.base.project.Project(project_root)
    rope.contrib.codeassist.get_calltip(
        project, """\
def foo():
       print(23)
      print(17)
        """, 24
    )

finally:
    shutil.rmtree(project_root)
```

Backtrace:

```
Traceback (most recent call last):
  File "foo.py", line 17, in <module>
    """, 24
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 92, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 46, in pyname_at
    pymodule = self.get_pymodule()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 34, in get_pymodule
    self.commenter.comment(e.lineno)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 78, in comment
    start = _logical_start(self.lines, lineno, check_prev=True) - 1
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 172, in _logical_start
    return logical_finder.logical_line_in(lineno)[0]
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/base/codeanalyze.py", line 183, in logical_line_in
    raise e
  File "<tokenize>", line 3
    print(17)
    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by mcepl** [comment]
Patches would be welcome and if reasonable then accepted, but otherwise, no ``rope`` never promised to fix broken syntax. We just use standard Python parser and so we break on the same code Python does.
