### ISSUE TITLE
Uncaught IndexError in code_assist

### ISSUE THREAD

**Issue by jorgenschaefer** [python-rope/rope#81]
This code generates an `IndexError`. I would expect Rope to simply not return any completions.

```Python
import shutil
import tempfile

import rope.base.project
import rope.contrib.codeassist


project_root = tempfile.mkdtemp()
try:

    project = rope.base.project.Project(project_root)
    rope.contrib.codeassist.code_assist(
        project, """\                                                           
from .. import foo                                                              
        """, 18
    )

finally:
    shutil.rmtree(project_root)
```

Backtrace:

```
Traceback (most recent call last):
  File "foo.py", line 15, in <module>
    """, 18
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 33, in code_assist
    return assist()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 321, in __call__
    completions = list(self._code_completions().values())
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 399, in _code_completions
    return self._from_import_completions(pymodule)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 363, in _from_import_completions
    pymodule = self._find_module(pymodule, module_name)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 373, in _find_module
    while module_name[dots] == '.':
IndexError: string index out of range
```

**Comment by mcepl** [comment]
The same logic as https://github.com/python-rope/rope/issues/80#issuecomment-152327450 ... where did you have cursor when initiating completion?

**Comment by mcepl** [comment]
The same logic as https://github.com/python-rope/rope/issues/80#issuecomment-152327450 and #83 ... where did you have cursor when initiating completion?
